Allow case-insensitive animal_project_code, network_project_code, station_name
inbo/etn pull request #144
Opened 2020-11-26 11:35 UTC by peterdesmet

- [x] Casts those input parameter to lowercase in functions that use them
- [x] Updates `list_` functions so it only returns lowercase values (I wonder if we should do that though)
- [ ] Make SQL in `get_` queries case-insensitive
- [ ] Add tests

2020-11-26 12:41 UTC, peterdesmet commented
@damianooldoni this is now implemented.

`list_` functions are still the same:

```
list_animal_project_codes()
 [1] "2010_phd_reubens"          "2010_phd_reubens_sync"     "2011_rivierprik"          
 [4] "2012_leopoldkanaal"        "2013_albertkanaal"         "2014_demer"               
 [7] "2015_Albertkanaal_VPS_Ham"
```

`get_` functions work now independent of case. Values in the returned df are as they are in the database:

```
> get_animals(con, animal_project_code = "2015_AlbertKANaal_vps_HAM")
# A tibble: 13 x 64
      pk animal_id animal_project_… tag_id tag_fk scientific_name common_name aphia_id animal_label
   <int>     <int> <chr>            <chr>  <chr>  <chr>           <chr>          <int> <chr>       
 1   650       650 2015_Albertkana… A69-1… 672    Sync tag        NA                NA NA          
```

Incorrect values still give an error, but the returned values in error message are lowercase (difficult to get around that, but fine I think):

```
get_animals(con, animal_project_code = "AlbertKANaal_vps_HAM")
 Error: Invalid value(s) for animal_project_code argument.
Valid inputs are: 2010_phd_reubens, 2010_phd_reubens_sync, 2011_rivierprik, 2012_leopoldkanaal, 2013_albertkanaal, 2014_demer, 2015_albertkanaal_vps_ham, 2015_dijle, 2015_fint, 2015_homarus, 2015_phd_verhelst_cod, 2015_phd_verhelst_eel, 2016_albertkanaal_vps_ham, 2016_phd_vergeynst, 2017_albertkanaal_vps_ham, 2017_iller, 2018_ec, 2018_iller, 2019_grotenete, adst-shark and others... 
```

Let me know if we should add tests for this too.

2020-12-05 19:10 UTC, damianooldoni requested changes
Nice work @peterdesmet!

I think it is only needed an improvement of documentation in section @example

2020-12-05 19:17 UTC, damianooldoni commented
@peterdesmet: I added tests but for get_animals() I cannot really check it due to the fact I don't have access to all projects. Could you run the tests, please? Thanks.

2020-12-10 12:32 UTC, damianooldoni commented
Now I have access to all projects, I could check the tests for get_animals() and they passed as expected.

I also changed the animal project used for testing `download_dataset()` as dataset output from  `2015_homarus` is changing over time quite often and I got again a new test failure. Changed to `2014_demer`, which is a closed project, so stable for testing.

@peterdesmet : to add to my previous review: would you plan to update package version? This new functionality deserves it, I think :+1:

2020-12-10 15:45 UTC, peterdesmet commented
You can bump to version number `0.1.0.9140`, where not quite at 0.2 yet

2020-12-10 15:48 UTC, peterdesmet commented on R/get_animals.R
> +#'   Case-insensitive.
Would have to do this for all functions I guess?

2021-01-04 15:55 UTC, damianooldoni commented on R/get_animals.R
> +#'   Case-insensitive.
Yes, I think so. :smile:

2021-01-04 15:59 UTC, peterdesmet commented on R/get_animals.R
> +#'   Case-insensitive.
Will be addressed in #147

2021-01-04 16:01 UTC, damianooldoni approved these changes
Great work

2021-01-04 16:01 UTC, merged

2021-01-04 16:01 UTC, damianooldoni commented
Merge @peterdesmet, please :+1: